# apiVersion: platform.crossplane.io/v1alpha1
# kind: CompositeGKECluster
# metadata:
#   name: my-composite-gke-cluster
# spec:
#   cluster_name: prod-cluster
#   location: us-central1
#   network_name: my-network
#   subnet_name: my-subnet
#   services_ipv4_cidr_block: 10.96.0.0/12
#   pods_ipv4_cidr_block: 10.244.0.0/16
#   machine_type: n1-standard-2
#   disk_size_gb: 100
#   node_count: 3



# apiVersion: platform.crossplane.io/v1alpha1
# kind: CompositeGKECluster
# metadata:
#   name: my-composite-gke-cluster
# spec:
#   parameters:
#     cluster_name: prod-cluster
#     location: us-central1
#     network_name: my-network
#     subnet_name: my-subnet
#     services_ipv4_cidr_block: 10.96.0.0/12
#     pods_ipv4_cidr_block: 10.244.0.0/16
#     machine_type: n1-standard-2
#     disk_size_gb: 100
#     node_count: 3


apiVersion: platform.crossplane.io/v1alpha1
kind: CompositeGKECluster
metadata:
  name: my-composite-gke-cluster
spec:  # Add spec here to match XRD
  cluster_name: prod-cluster
  location: us-central1
  network_name: my-network
  subnet_name: my-subnet
  services_ipv4_cidr_block: 10.96.0.0/12
  pods_ipv4_cidr_block: 10.244.0.0/16
  machine_type: n1-standard-2
  disk_size_gb: 100
  node_count: 3
