apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositetkgcluster
spec:
  group: platform.crossplane.io
  names:
    kind: CompositeGKECluster
    plural: compositegkeclusters
  claimNames:
    kind: GKEClusterClaim
    plural: gkeclusterclaims
  version: v1
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
  connectionSecretKeys:
    - name: kubeconfig
    - name: endpoint
  spec:
    schema:
      openAPIV3Schema:
        type: object
        properties:
          cluster_name:
            type: string
          network_name:
            type: string
          subnet_name:
            type: string
          location:
            type: string
          services_ipv4_cidr_block:
            type: string
          pods_ipv4_cidr_block:
            type: string
          node_count:
            type: integer
          machine_type:
            type: string
          disk_size_gb:
            type: integer
