apiVersion: networking.gcp.crossplane.io/v1alpha1
kind: CompositeNetwork
metadata:
  name: my-composite-network
spec:
  compositionRef:
    name: network-composition
  parameters:
    vpc_name: "my-vpc"
    subnet_cidr_range: "10.0.0.0/24"
    region: "us-central1"
    cluster_master_ip_cidr_range: "10.0.0.0/28"
    cluster_pods_ip_cidr_range: "10.0.1.0/24"
    cluster_services_ip_cidr_range: "10.0.2.0/24"
