apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: network-composition
spec:
  compositeTypeRef:
    apiVersion: networking.gcp.crossplane.io/v1alpha1
    kind: CompositeNetwork
  resources:
    - name: vpc
      base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: Network
        spec:
          forProvider:
            name: "{{ .parameters.vpc_name }}"
            autoCreateSubnetworks: false
            routingConfig:
              routingMode: GLOBAL
          providerConfigRef:
            name: gcp-provider

    - name: subnet
      base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: Subnetwork
        spec:
          forProvider:
            name: "{{ .parameters.vpc_name }}-subnet"
            ipCidrRange: "{{ .parameters.subnet_cidr_range }}"
            region: "{{ .parameters.region }}"
            networkRef:
              name: "{{ .parameters.vpc_name }}"
            privateIpGoogleAccess: true
          providerConfigRef:
            name: gcp-provider

    - name: router
      base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: Router
        spec:
          forProvider:
            name: "{{ .parameters.vpc_name }}-router"
            network: "{{ .parameters.vpc_name }}"
            region: "{{ .parameters.region }}"
          providerConfigRef:
            name: gcp-provider

    - name: ip-address
      base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: Address
        spec:
          forProvider:
            name: "{{ .parameters.vpc_name }}-nat-gateway"
            region: "{{ .parameters.region }}"
          providerConfigRef:
            name: gcp-provider

    - name: nat-gateway
      base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: RouterNAT
        spec:
          forProvider:
            name: "{{ .parameters.vpc_name }}-nat-router"
            router: "{{ .parameters.vpc_name }}-router"
            region: "{{ .parameters.region }}"
            natIps:
              - "{{ .resources.ip-address.status.atProvider.selfLink }}"
            sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
            logConfig:
              enable: true
              filter: ERRORS_ONLY
          providerConfigRef:
            name: gcp-provider

    - name: route
      base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: Route
        spec:
          forProvider:
            name: "{{ .parameters.vpc_name }}-egress-internet"
            network: "{{ .parameters.vpc_name }}"
            destRange: "0.0.0.0/0"
            nextHopGateway: default-internet-gateway
          providerConfigRef:
            name: gcp-provider
